controllers/AuthController.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: maksim
 * Date: 03.06.18
 * Time: 13:24
 */

namespace app\controllers;

use app\models\LoginForm;
use app\models\User;
use Yii;
use app\models\SignupForm;

/**
 * Class AuthController
 * @package app\controllers
 */
class AuthController extends \yii\web\Controller
{
    /**
     * @return string|\yii\web\Response
     * @throws \yii\base\Exception
     */
    public function actionSignup()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['transfer/index']);
        }

        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = new User();
            $user->email = $model->email;
            $user->name = $model->name;
            $user->password = Yii::$app->security->generatePasswordHash($model->password);
            $user->balance = 100000;
            $user->save();

            return $this->redirect(['auth/login']);
        } else {
            return $this->render('signup.php', ['model' => $model]);
        }
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['transfer/index']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['transfer/index']);
        }

        $model->password = '';
        return $this->render('login.php', [
            'model' => $model,
        ]);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        if (!Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
        }

        return $this->redirect(['auth/login']);
    }
}

controllers/TransferController.php
<?php

namespace app\controllers;

use app\models\CreateTransferForm;
use app\models\Transfer;
use app\models\User;
use Yii;

/**
 * Class TransferController
 * @package app\controllers
 */
class TransferController extends \yii\web\Controller
{
    /**
     * @return string|\yii\web\Response
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['auth/login']);
        }

        $currentUser = $this->getCurrentUser();

        return $this->render('index', [
            'inputTransfers' => $this->getTransfersWithEmails($currentUser->inputTransfers, 'in'),
            'outputTransfers' => $this->getTransfersWithEmails($currentUser->outputTransfers, 'out')
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['auth/login']);
        }

        $model = new CreateTransferForm();

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            $currentUser = $this->getCurrentUser();
            $transferUser = User::findOne([
                'email' => $model->to_email
            ]);

            $currentUser->balance -= $model->amount;
            $currentUser->save();

            $commissionSum = Transfer::getCommissionSum($model->amount);
            $model->amount -= $commissionSum;

            $transfer = new Transfer();
            $transfer->link('fromUser', $currentUser);
            $transfer->link('toUser', $transferUser);
            $transfer->amount = $model->amount;
            $transfer->save();

            $transferUser->balance += $model->amount;
            $transferUser->save();

            return $this->redirect(['transfer/index']);
        }

        return $this->render('create', [
            'model' => $model,
            'commissions' => Transfer::$commissions
        ]);
    }

    /**
     * @param array $transfers
     * @param string $type
     * @return array
     */
    private function getTransfersWithEmails($transfers, $type)
    {
        $currentUser = $this->getCurrentUser();

        $transfersWithEmails = [];

        foreach ($transfers as $transfer) {
            $transferWithEmail = [
                'from' => '',
                'to' => '',
                'amount' => $transfer->amount,
                'created_at' => $transfer->created_at
            ];

            if ($type === 'in') {
                $transferWithEmail['from'] = User::find()
                    ->select('email')
                    ->where(['id' => $transfer->from_id])
                    ->one()
                    ->email;
                $transferWithEmail['to'] = $currentUser->email;
            } elseif ($type === 'out') {
                $transferWithEmail['from'] = $currentUser->email;
                $transferWithEmail['to'] = User::find()
                    ->select('email')
                    ->where(['id' => $transfer->to_id])
                    ->one()
                    ->email;
            }

            array_push($transfersWithEmails, $transferWithEmail);
        }

        return $transfersWithEmails;
    }

    /**
     * @return User|null
     */
    private function getCurrentUser()
    {
        return User::findOne(\Yii::$app->user->id);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Переводы',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Войти', 'url' => ['/auth/login']];
        $menuItems[] = ['label' => 'Регистарация', 'url' => ['/auth/signup']];
    } else {
        $menuItems[] = ['label' => 'Переводы', 'url' => ['/transfer/index']];
        $menuItems[] = ['label' => 'Новый перевод', 'url' => ['/transfer/create']];
        $menuItems[] = '<li>'
            . Html::beginForm(['/auth/logout'], 'post')
            . Html::submitButton(
                'Выйти (' . Yii::$app->user->identity->name . ' ' . Yii::$app->user->identity->balance . ' руб)',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>